export const ContentInfoTop = [
  {
    circleTopName: 'STEP',
    circleSpanName: '01',
    circleBottomName: '卸粧',
    img: 'hoge',
    contentTitle: 'MCO速淨卸粧油 BLACK＆SMOOTH 120ml',
    contentSentence:
      '適用於有毛孔護理需求的朋友，推薦給「在意鼻翼汙垢」、「希望膚質更加柔滑細緻」的您！',
  },
  {
    circleTopName: 'STEP',
    circleSpanName: '02',
    circleBottomName: '潔膚',
    img: 'hoge',
    contentTitle: '毛孔淨化潔膚泥膠　120g',
    contentSentence: '每天持續使用，可為毛孔深層淨污，再現光滑細緻膚質。',
  },
  {
    circleTopName: 'STEP',
    circleSpanName: '03',
    circleBottomName: '化妝水',
    img: 'hoge',
    contentTitle: '亮白化妝水 滋潤型〈藥用化妝品〉 30ml',
    contentSentence: '滋潤型藥用美白化妝水，為您打造健康勻淨的透亮美肌。',
  },
  {
    circleTopName: 'STEP',
    circleSpanName: '04',
    circleBottomName: '精華露',
    img: 'hoge',
    contentTitle: '美白透亮精華露〈藥用化妝品〉 18ml',
    contentSentence: '直達黑斑根源進行修護，實現透亮美肌。',
  },
  {
    circleTopName: 'STEP',
    circleSpanName: '05',
    circleBottomName: '乳液',
    img: 'hoge',
    contentTitle: '亮白乳液 滋潤型〈藥用化妝品〉 30ml',
    contentSentence: '滋潤型藥用美白乳液，為您打造水潤持久的透亮美肌。',
  },
  {
    circleTopName: 'STEP',
    circleSpanName: '06',
    circleBottomName: '面膜',
    img: 'hoge',
    contentTitle: '活膚祛黑精華面膜 6片',
    contentSentence: '一片面膜蘊含1瓶以上的美白精華液。',
  },
  {
    circleTopName: 'STEP',
    circleSpanName: '07',
    circleBottomName: '防曬',
    img: 'hoge',
    contentTitle: '長效清透防曬露50+ (SPF50 PA++++) 60ml',
    contentSentence: '高效耐水抗汗，並阻隔強烈紫外線與外來刺激！',
  },
  {
    circleTopName: '贈品',
    circleSpanName: '',
    circleBottomName: '防曬',
    img: 'hoge',
    contentTitle: 'MCO速淨卸粧油 120ml',
    contentSentence:
      '宛如精華液般「親膚柔滑」的油性質地，無須摩擦即可卸除。打造看不見毛孔的水嫩柔滑肌。',
  },
];
