export const RegionKansaiChugokuInfo = [
  {
    img: '../../src/img/Region/KansaiChugoku/eat/1.jpeg',
    title: '瀨戶內檸檬農園',
    content: '海苔花枝脆餅 檸檬辣醬口味（廣島 ）',
    moneyTitle: 'NT$64.8',
    moneyContent: 'JPY300',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/2.jpeg',
    title: '瀨戶內檸檬農園',
    content: '蜂蜜漬檸檬片（廣島 ）',
    moneyTitle: 'NT$215.7',
    moneyContent: 'JPY1,000',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/3.jpeg',
    title: '瀨戶內檸檬農園',
    content: '花枝脆餅 檸檬辣醬口味（廣島 ）',
    moneyTitle: 'NT$64.8',
    moneyContent: 'JPY300',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/4.jpeg',
    title: '瀨戶內檸檬農園',
    content: '橙花蜂蜜瀨戶內檸檬水（稀釋用）（廣島 ）',
    moneyTitle: 'NT$215.7',
    moneyContent: 'JPY1000',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/5.jpeg',
    title: '瀨戶內檸檬農園',
    content: '黃金魷魚絲（廣島 ）',
    moneyTitle: 'NT$38.9',
    moneyContent: 'JPY180',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/6.jpeg',
    title: '瀨戶內檸檬農園',
    content: '福之魷魚絲（廣島 ）',
    moneyTitle: 'NT$38.9',
    moneyContent: 'JPY180',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/7.jpeg',
    title: '美樂圓餅',
    content: '野村 美樂圓餅 松露口味4連包 30g×4（高知）',
    moneyTitle: 'NT$54',
    moneyContent: 'JPY250',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/8.jpeg',
    title: '神戶樽五',
    content: '明石章魚仙貝 12片入（兵庫）',
    moneyTitle: 'NT$156.4',
    moneyContent: 'JPY725',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/9.jpeg',
    title: '神戶樽五',
    content: '明石章魚仙貝 24片入（兵庫）',
    moneyTitle: 'NT$312.8',
    moneyContent: 'JPY1,450',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/10.jpeg',
    title: '神戶樽五',
    content: '章魚洋蔥仙貝（兵庫)',
    moneyTitle: 'NT$129.5',
    moneyContent: 'JPY600',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/11.jpeg',
    title: '御菓子司 本家菊屋',
    content: '蕨羹1個裝（奈良）',
    moneyTitle: 'NT$69.9',
    moneyContent: 'JPY324',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/12.jpeg',
    title: 'SETOUCHI Maruka-marche',
    content: '幸福蒜香奶油海苔脆餅（廣島)',
    moneyTitle: 'NT$75.5',
    moneyContent: 'JPY350',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/13.jpeg',
    title: 'SETOUCHI Maruka-marche',
    content: '魷魚脆餅 蜂蜜芥末味（廣島）',
    moneyTitle: 'NT$60.4',
    moneyContent: 'JPY280',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/14.jpeg',
    title: '福壽園',
    content: '抹茶蕨餅 4個入（京都)',
    moneyTitle: 'NT$332.2',
    moneyContent: 'JPY1,540',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/15.jpeg',
    title: '福壽園',
    content: '抹茶布丁 4個入（京都）',
    moneyTitle: 'NT$332.2',
    moneyContent: 'JPY1540',
  },
  {
    img: '../../src/img/Region/KansaiChugoku/eat/16.jpeg',
    title: '福壽園',
    content: '京之抹茶牛奶糖 宇治HINERI 4盒入（京都）',
    moneyTitle: 'NT$375.3',
    moneyContent: 'JPY1,740',
  },
];
