export const RegionKyushuOkinawaInfo = [
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/1.jpeg',
    title: '沖繩南風堂',
    content: '沖繩鹽焦糖堅果脆餅（小）（沖繩）',
    moneyTitle: 'NT$168.5',
    moneyContent: 'JPY780',
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/2.jpeg',
    title: '沖繩南風堂',
    content: '石垣島辣油洋芋片（沖繩）',
    moneyTitle: 'NT$64.8',
    moneyContent: 'JPY300',
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/3.jpeg',
    title: '沖繩南風堂',
    content: '宮古牛洋芋片（60g）（沖繩）',
    moneyTitle: 'NT$64.8',
    moneyContent: 'JPY300',
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/4.jpeg',
    title: '沖繩南風堂',
    content: '八島黑糖（沖繩）',
    moneyTitle: 'NT$172.6',
    moneyContent: 'JPY800',
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/5.jpeg',
    title: '沖繩南風堂',
    content: '琉球拉麵豚骨醬油口味（小）（沖繩）',
    moneyTitle: 'NT$151',
    moneyContent: 'JPY700',
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/6.jpeg',
    title: '沖繩南風堂',
    content: '雪鹽金楚糕（大）（沖繩）（沖繩）',
    moneyTitle: 'NT$215.7',
    moneyContent: 'JPY1,000',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/7.jpeg',
    title: '沖繩南風堂',
    content: '島唐辛子辣味蝦餅（小）（沖繩）',
    moneyTitle: 'NT$129.5',
    moneyContent: 'JPY600',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/8.jpeg',
    title: 'Calbee Plus',
    content: '沖繩限定黑糖薯塊（18g×8包）',
    moneyTitle: 'NT$188.5',
    moneyContent: 'JPY860',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/9.jpeg',
    title: '沖繩南風堂',
    content: '雪鹽金楚糕5種口味禮盒（小）（沖繩）',
    moneyTitle: 'NT$129.5',
    moneyContent: 'JPY600',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/10.jpeg',
    title: '沖繩南風堂',
    content: '花生豆腐3包裝（沖繩）',
    moneyTitle: 'NT$142.4',
    moneyContent: 'JPY660',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/11.jpeg',
    title: 'iichiko',
    content: 'iichiko 本格麥燒酌 Frasco 720ml',
    moneyTitle: 'NT$610',
    moneyContent: 'JPY2,828',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/12.jpeg',
    title: 'Craftsman多田',
    content: 'Craftsman多田 麥燒酎 Chianti brown 720ml',
    moneyTitle: 'NT$334.4',
    moneyContent: '1,550',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/13.jpeg',
    title: 'iichiko',
    content: 'iichiko 本格麥燒酌 Special 720ml',
    moneyTitle: 'NT$542.5',
    moneyContent: 'JPY2,515',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/14.jpeg',
    title: 'iichiko',
    content: 'iichiko 本格麥燒酌 空山獨酌 720ml',
    moneyTitle: 'NT464.9',
    moneyContent: 'JPY2,160',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/15.jpeg',
    title: '篠崎',
    content: '千年之眠 麥燒酌 720ml',
    moneyTitle: 'NT$627.5',
    moneyContent: 'JPY2,909',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KyushuOkinawa/eat/16.jpeg',
    title: '光酒造',
    content: '夢想仙樂 麥燒酌 720ml',
    moneyTitle: 'NT$642.8',
    moneyContent: 'JPY2,980',
    isCart: false,
  },
];
