export const RegionTokaiHokurikuuInfo = [
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/1.jpeg',
    title: '柿之種米果',
    content: '北陸限定 龜田白丁蝦風味 柿種米果',
    moneyTitle: 'NT$129.5',
    moneyContent: 'JPY600',
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/2.jpeg',
    title: 'Shinyonezawa',
    content: '靜岡皇冠哈密瓜果凍 8個入（含3支特製金湯匙）（愛知）',
    moneyTitle: 'NT$862.8',
    moneyContent: 'JPY4,000',
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/3.jpeg',
    title: 'cocco',
    content: 'cocco 小雞蒸蛋糕 8個入（靜岡）',
    moneyTitle: 'NT$215.7',
    moneyContent: 'JPY1000',
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/4.jpeg',
    title: 'cocco',
    content: 'cocco 小雞蒸蛋糕 2個入（靜岡）',
    moneyTitle: 'NT$54',
    moneyContent: 'JPY250',
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/5.jpeg',
    title: '安倍川麻糬',
    content: '安倍川麻糬 6包（靜岡)',
    moneyTitle: 'NT$258.9',
    moneyContent: 'JPY1,200',
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/6.jpeg',
    title: '安倍川麻糬',
    content: '安倍川麻糬 4包（靜岡)',
    moneyTitle: 'NT$172.6',
    moneyContent: 'JPY800',
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/7.jpeg',
    title: '安倍川麻糬',
    content: '安倍川麻糬 1包（靜岡)',
    moneyTitle: 'NT$43.2',
    moneyContent: 'JPY200',
    isCart: false,
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/8.jpeg',
    title: 'cocco',
    content: '小雞蒸蛋糕 綜合口味（靜岡）',
    moneyTitle: 'NT$366.7',
    moneyContent: 'JPY1,700',
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/9.jpeg',
    title: 'cocco',
    content: '小雞蒸蛋糕 濃抹茶口味 6個入（靜岡）',
    moneyTitle: 'NT$194.2',
    moneyContent: 'JPY900',
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/10.jpeg',
    title: '菊姫',
    content: '菊姬「菊理媛」大吟釀 720ml',
    moneyTitle: 'NT$5,154.8',
    moneyContent: 'JPY23,900',
    isCart: false,
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/11.jpeg',
    title: '菊姫',
    content: '菊姬　大吟釀 720ml',
    moneyTitle: 'NT$1,251',
    moneyContent: 'JPY5,800',
    isCart: false,
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/12.jpeg',
    title: '菊姫',
    content: '菊姬「黑吟」大吟釀 720ml',
    moneyTitle: 'NT$3,084.2',
    moneyContent: '14,300',
    isCart: false,
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/13.jpeg',
    title: '菊姫',
    content: '菊姬「吟」大吟釀 720ml',
    moneyTitle: 'NT$2,070.6',
    moneyContent: 'JPY9,600',
    isCart: false,
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/14.jpeg',
    title: '小布施堂',
    content: '水栗羊羹(3個入)（長野）',
    moneyTitle: 'NT2,070.6',
    moneyContent: 'JPY1,270',
    isCart: false,
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/15.jpeg',
    title: '手取川',
    content: '手取川「名流」大吟釀 720ml',
    moneyTitle: 'NT$603.9',
    moneyContent: 'JPY2,800',
    isCart: false,
  },
  {
    img: '../../src/img/Region/TokaiHokuriku/eat/16.jpeg',
    title: '傳心',
    content: '傳心「雪」純米吟釀 720ml',
    moneyTitle: 'NT$345.1',
    moneyContent: 'JPY1,600',
    isCart: false,
  },
];
