export const RegionHokkaidoTohokuInfo = [
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/1.jpeg',
    title: '柿之種米果',
    content: '東北限定 龜田牛舌風味柿種米果',
    moneyTitle: 'NT$117.1',
    moneyContent: 'JPY540',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/2.jpeg',
    title: 'ISHIYA G',
    content: 'Saqu LANGUE DE CHAT 18片混裝',
    moneyTitle: 'NT$433.6',
    moneyContent: 'JPY2,000',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/3.jpeg',
    title: 'Hatoya',
    content: '海鮮茶泡飯3個（青森）',
    moneyTitle: 'NT$227.7',
    moneyContent: 'JPY1,050',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/4.jpeg',
    title: 'Hatoya',
    content: '海鮮茶泡飯1個',
    moneyTitle: 'NT$65.1',
    moneyContent: 'JPY300',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/5.jpeg',
    title: 'Hatoya',
    content: '繩文遺跡餅乾5片裝（青森）',
    moneyTitle: 'NT$141',
    moneyContent: 'JPY650',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/6.jpeg',
    title: 'Hatoya',
    content: '厚切青森蘋果乾（富士蘋果）1包2片（青森）',
    moneyTitle: 'NT$43.4',
    moneyContent: 'JPY200',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/7.jpeg',
    title: '柿之種米果',
    content: '東北限定 龜田烤魷魚醬油美乃滋風味 柿種米果',
    moneyTitle: 'NT$117.1',
    moneyContent: 'JPY540',
    isCart: false,
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/8.jpeg',
    title: 'ISHIYA G',
    content: 'Saqu LANGUE DE CHAT 30片混裝',
    moneyTitle: 'NT$693.7',
    moneyContent: 'JPY3,200',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/9.jpeg',
    title: '巖手屋',
    content: '老奶奶南部煎餅 花生口味（岩手）',
    moneyTitle: 'NT$75.3',
    moneyContent: 'JPY347',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/10.jpeg',
    title: '巖手屋',
    content: '南部之薰 10種20片（岩手）',
    moneyTitle: 'NT$368.6',
    moneyContent: 'JPY1,700',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/11.jpeg',
    title: '巖手屋',
    content: 'Nico Nico 南部煎餅（岩手）',
    moneyTitle: 'NT$125.3',
    moneyContent: 'JPY578',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/12.jpeg',
    title: '巖手屋',
    content: '蘋果煎餅6片裝',
    moneyTitle: 'NT$130.1',
    moneyContent: 'JPY600',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/13.jpeg',
    title: '巖手屋',
    content: '魷魚煎餅6片裝',
    moneyTitle: 'NT$130.1',
    moneyContent: 'JPY600',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/14.jpeg',
    title: '巖手屋',
    content: '老奶奶南部煎餅 芝麻口味（岩手)',
    moneyTitle: 'NT$75.3',
    moneyContent: 'JPY347',
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/15.jpeg',
    title: 'Hatoya',
    content: '青森紅玉蘋果起司蛋糕 3個裝（青森）',
    moneyTitle: 'NT$145.3',
    moneyContent: 'JPY670',
    isCart: false,
  },
  {
    img: '../../src/img/Region/HokkaidoTohoku/eat/16.jpeg',
    title: 'RAGUENEAU',
    content: '旅行中的幸福蘋果派 10個裝（青森）',
    moneyTitle: 'NT$401.3',
    moneyContent: 'JPY1,851',
  },
];
