export const RegionKantoKosinetuInfo = [
  {
    img: '../../src/img/Region/KantoKosinetu/eat/1.jpeg',
    title: 'AND THE FRIET',
    content: '薯條餅乾迷你禮盒 10入',
    moneyTitle: 'NT$519.4',
    moneyContent: 'JPY2,408',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/2.jpeg',
    title: '柿之種米果',
    content: '信州限定 龜田山葵風味 柿種米果',
    moneyTitle: 'NT$129.5',
    moneyContent: 'JPY600',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/3.jpeg',
    title: '柿之種米果',
    content: '橫濱限定 龜田四川麻婆豆腐風味 柿種米果',
    moneyTitle: 'NT$116.5',
    moneyContent: 'JPY540',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/4.jpeg',
    title: '柿之種米果',
    content: '那須限定 龜田美味起司風味 柿種米果',
    moneyTitle: 'NT$116.5',
    moneyContent: 'JPY540',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/5.jpeg',
    title: 'AND THE FRIET',
    content: '薯條餅乾迷你禮盒 5入',
    moneyTitle: 'NT$279.8',
    moneyContent: 'JPY1,297',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/6.jpeg',
    title: 'AND THE FRIET',
    content: '薯條餅乾迷你禮盒 12入',
    moneyTitle: 'NT$623.1',
    moneyContent: 'JPY2,889',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/7.jpeg',
    title: '八幡屋礒五郎',
    content: '七味胡麻辣油（長野）',
    moneyTitle: 'NT$135.9',
    moneyContent: 'JPY630',
    isCart: false,
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/8.jpeg',
    title: '柿之種米果',
    content: '千葉限定 龜田勝浦擔擔麵風味 柿種米果',
    moneyTitle: 'NT$116.5',
    moneyContent: 'JPY540',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/9.jpeg',
    title: '小布施堂',
    content: '迷你栗羊羹(6入裝)（長野）',
    moneyTitle: 'NT$302',
    moneyContent: 'JPY1,400',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/10.jpeg',
    title: '小布施堂',
    content: '迷你栗鹿子羊羹(6入裝)（長野））',
    moneyTitle: 'NT$358.1',
    moneyContent: 'JPY1,660',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/11.jpeg',
    title: '小布施堂',
    content: '栗鹿子(小)（長野）',
    moneyTitle: 'NT$345.1',
    moneyContent: 'JPY1,600',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/12.jpeg',
    title: '小布施堂',
    content: '栗鹿子 迷你(3個裝)（長野)',
    moneyTitle: 'NT$390.4',
    moneyContent: 'JPY1,810',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/13.jpeg',
    title: '小布施堂',
    content: '栗鹿子 迷你(6個裝)（長野）',
    moneyTitle: 'NT$759.2',
    moneyContent: 'JPY3,520',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/14.jpeg',
    title: '小布施堂',
    content: '水栗羊羹(3個入)（長野）',
    moneyTitle: 'NT$274',
    moneyContent: 'JPY1,270',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/15.jpeg',
    title: '小布施堂',
    content: '水栗羊羹(6個入)（長野）',
    moneyTitle: 'NT$526.3',
    moneyContent: 'JPY2,440',
  },
  {
    img: '../../src/img/Region/KantoKosinetu/eat/16.jpeg',
    title: '柿之種米果',
    content: '東京限定　龜田土產柿之種',
    moneyTitle: 'NT$258.9',
    moneyContent: 'JPY1,200',
  },
];
